
export const LOAD_QUESTIONS_REQUEST = 'LOAD_QUESTIONS_REQUEST';
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const LOAD_QUESTIONS_ERROR = 'LOAD_QUESTIONS_ERROR';

//home
export const LOAD_CHAPTERS = 'LOAD_CHAPTERS';

//chapter
export const LOAD_SUBJECTS = 'LOAD_SUBJECTS';

//subject
export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
export const SELECT_RADIO_QUESTION = 'SELECT_RADIO_QUESTION';
export const SELECT_CHECKBOX_QUESTION = 'SELECT_CHECKBOX_QUESTION';
